version: "3"

tasks:
  dev:
    cmds:
      - air
  docs:
    cmds:
      - swag i --d ./cmd/http,./pkg/database,./internal
  build:
    cmds:
      - go build -gcflags="all=-N -l" ./cmd/http/main.go
  preview:
    cmds:
      - ./main.exe